// app/layout.tsx
import type { Metadata } from "next"
import { Inter, Poppins } from "next/font/google"
import "./globals.css"
import { Navbar } from "@/components/common/Navbar"
import { ThemeProvider } from "next-themes"
import { NavbarWrapper } from "@/components/NavbarWrapper"
// import { usePathname } from "next/navigation"

const inter = Inter({ subsets: ["latin"] })
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "700"] })

export const metadata: Metadata = {
  title: "HearSafe",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Check if current page is signin or signup
  const hideNavbar = 
    typeof window !== 'undefined' && 
    (window.location.pathname === '/signin' || 
     window.location.pathname === '/signup' || window.location.pathname.startsWith('/test'))

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Material Symbols */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
        />
      </head>
      <body className={inter.className}>
        {/* ✅ Wrap everything inside ThemeProvider */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* {!hideNavbar && <Navbar />} */}
          <NavbarWrapper/>
          <main className="p-6">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}